version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - n 16
            - "npm install yarn -g"
            - "yarn config set ignore-engines true"
            - "npm install selenium-webdriver"
    build:
        commands:
            - node test-ui-devicefarm.js