version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 12
    build:
        commands:
            - aws s3 sync ./  s3://[[BUCKET_NAME]]/  --delete  --region [[REGION]]
            - aws cloudfront create-invalidation --distribution-id [[DIST_ID]] --paths "/*"
artifacts:
    files:
        - "**/*"
    base-directory: ./