version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g newman
      - yum install -y jq
  build:
    commands:
      - newman run Demogo-User.postman_collection.json -r junit
reports:
  JUnitReports:
    files:
      - '**/*'
    base-directory: './newman'